/*
 *<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<    DIO_config.h    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 *
 *  Author : ABDELHADY ELSHAHAT ABDELHADY
 *  Layer  : MCAL
 *  SWD    : DIO
 *
 */
#ifndef MCAL_DIO_DIO_CONFIG_H_
#define MCAL_DIO_DIO_CONFIG_H_

/* <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Macros for Initial Pin Direction >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>*/

/*Macros for PORTA Initial Directions --> options [DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT ,DIO_u8_PIN_INTIAL_DIRECTION_INPUT ]*/
#define DIO_u8_PA0_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PA1_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PA2_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PA3_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PA4_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PA5_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PA6_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PA7_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT


/*Macros for PORTB Initial Directions --> options [DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT ,DIO_u8_PIN_INTIAL_DIRECTION_INPUT ] */
#define DIO_u8_PB0_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PB1_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PB2_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PB3_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PB4_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PB5_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PB6_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PB7_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT

/*Macros for PORTC Initial Directions --> options [DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT ,DIO_u8_PIN_INTIAL_DIRECTION_INPUT ] */
#define DIO_u8_PC0_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PC1_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PC2_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PC3_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_INPUT
#define DIO_u8_PC4_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PC5_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PC6_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PC7_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT

/*Macros for PORTD Initial Directions --> options [DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT ,DIO_u8_PIN_INTIAL_DIRECTION_INPUT ] */
#define DIO_u8_PD0_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PD1_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PD2_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PD3_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PD4_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PD5_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PD6_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT
#define DIO_u8_PD7_INTIAL_DIRECTION           DIO_u8_PIN_INTIAL_DIRECTION_OUTPUT

/* <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Macros for Initial Pin Value >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>*/

/*Macros for PORTA Initial values --> options [DIO_u8_PIN_INTIAL_VALUE_LOW ,
 * 											   DIO_u8_PIN_INTIAL_VALUE_HIGH,
 * 											   DIO_u8_PIN_INTIAL_VALUE_PULLUP,
 * 											   DIO_u8_PIN_INTIAL_VALUE_FLOATING ]*/
#define DIO_u8_PA0_INTIAL_VALUE           	 DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PA1_INTIAL_VALUE          	 DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PA2_INTIAL_VALUE          	 DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PA3_INTIAL_VALUE          	 DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PA4_INTIAL_VALUE          	 DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PA5_INTIAL_VALUE          	 DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PA6_INTIAL_VALUE          	 DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PA7_INTIAL_VALUE          	 DIO_u8_PIN_INTIAL_VALUE_LOW

/*Macros for PORTB Initial values --> options [DIO_u8_PIN_INTIAL_VALUE_LOW ,
 * 											   DIO_u8_PIN_INTIAL_VALUE_HIGH,
 * 											   DIO_u8_PIN_INTIAL_VALUE_PULLUP,
 * 											   DIO_u8_PIN_INTIAL_VALUE_FLOATING ]*/

#define DIO_u8_PB0_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PB1_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PB2_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PB3_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PB4_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PB5_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PB6_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PB7_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW


/*Macros for PORTB Initial values --> options [DIO_u8_PIN_INTIAL_VALUE_LOW ,
 * 											   DIO_u8_PIN_INTIAL_VALUE_HIGH,
 * 											   DIO_u8_PIN_INTIAL_VALUE_PULLUP,
 * 											   DIO_u8_PIN_INTIAL_VALUE_FLOATING ]*/

#define DIO_u8_PC0_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PC1_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PC2_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PC3_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_PULLUP
#define DIO_u8_PC4_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PC5_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PC6_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PC7_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW


/*Macros for PORTB Initial values --> options [DIO_u8_PIN_INTIAL_VALUE_LOW ,
 * 											   DIO_u8_PIN_INTIAL_VALUE_HIGH,
 * 											   DIO_u8_PIN_INTIAL_VALUE_PULLUP,
 * 											   DIO_u8_PIN_INTIAL_VALUE_FLOATING ]*/

#define DIO_u8_PD0_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PD1_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PD2_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PD3_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PD4_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PD5_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PD6_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW
#define DIO_u8_PD7_INTIAL_VALUE           DIO_u8_PIN_INTIAL_VALUE_LOW




#endif /* MCAL_DIO_DIO_CONFIG_H_ */
